In [5]:
import pandas as pd
df = pd.DataFrame(["Мама мыла раму, потом пошла обедать.", "Рама мыла маму, что очень странно.", "Мыло мыло маму, забавно получается.", "Раму мыла мама, а я гулял."], columns = ['text'])
df

                                   text
0  Мама мыла раму, потом пошла обедать.
1    Рама мыла маму, что очень странно.
2   Мыло мыло маму, забавно получается.
3            Раму мыла мама, а я гулял.

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

corpus = [
          'Text of first document Text Text.',
          'Text of the second document made longer.',
          'Number three.',
          'This is number four.',
]

X = vectorizer.fit_transform(df.text)

print(vectorizer.get_feature_names())

X.toarray()

['гулял', 'забавно', 'мама', 'маму', 'мыла', 'мыло', 'обедать', 'очень', 'получается', 'потом', 'пошла', 'рама', 'раму', 'странно', 'что']

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

array([[0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
       [0, 1, 0, 1, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]])

In [12]:
train = pd.DataFrame(data =X.toarray(), columns=vectorizer.get_feature_names())

train

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,гулял,забавно,мама,маму,мыла,мыло,обедать,очень,получается,потом,пошла,рама,раму,странно,что
0,0,0,1,0,1,0,1,0,0,1,1,0,1,0,0
1,0,0,0,1,1,0,0,1,0,0,0,1,0,1,1
2,0,1,0,1,0,2,0,0,1,0,0,0,0,0,0
3,1,0,1,0,1,0,0,0,0,0,0,0,1,0,0

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

# токенезация текста и построение словоря
vectorizer.fit(df.text)

# summarize
print(vectorizer.vocabulary_)
print(vectorizer.idf_)

{'мама': 2, 'мыла': 4, 'раму': 12, 'потом': 9, 'пошла': 10, 'обедать': 6, 'рама': 11, 'маму': 3, 'что': 14, 'очень': 7, 'странно': 13, 'мыло': 5, 'забавно': 1, 'получается': 8, 'гулял': 0}
[1.91629073 1.91629073 1.51082562 1.51082562 1.22314355 1.91629073
 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073
 1.51082562 1.91629073 1.91629073]

In [15]:
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform(df.text)

feature_names = vectorizer.get_feature_names()
print("Feature names", feature_names)

dense = vectors.todense()

denselist = dense.tolist()

df2 = pd.DataFrame(denselist, columns=feature_names)
df2

Feature names ['гулял', 'забавно', 'мама', 'маму', 'мыла', 'мыло', 'обедать', 'очень', 'получается', 'потом', 'пошла', 'рама', 'раму', 'странно', 'что']

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,гулял,забавно,мама,маму,мыла,мыло,обедать,очень,получается,потом,пошла,рама,раму,странно,что
0,0.000000,0.000000,0.365594,0.000000,0.295980,0.000000,0.463709,0.000000,0.000000,0.463709,0.463709,0.000000,0.365594,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.351570,0.284626,0.000000,0.000000,0.445922,0.000000,0.000000,0.000000,0.445922,0.000000,0.445922,0.445922
2,0.000000,0.388614,0.000000,0.306388,0.000000,0.777229,0.000000,0.000000,0.388614,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.614226,0.000000,0.484263,0.000000,0.392053,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.484263,0.000000,0.000000