In [46]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, plot_confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

In [47]:
from google.colab import files
uploaded = files.upload()

Saving example.csv to example (1).csv
Saving predict.csv to predict (1).csv
Saving train.csv to train (1).csv

In [74]:
train = pd.read_csv('train.csv')
test = pd.read_csv('predict.csv')

In [49]:
import re 
#re.findall(r'[A-z]\d([A-Za-z]*)', 'A0V')
train['first_bukva'] = 0
train['first_classification'] = 0
train['second_classification'] = 0
for index, row in train.iterrows():
  train.loc[index, 'first_bukva'] = re.split(r'\d', train.loc[index, 'SpType'])[0]
  try:
    a = re.findall(r'.*[0-9]([IV]*)', train.loc[index, 'SpType'])[-1]
    if a  not in ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII']:
      train.loc[index, 'first_classification'] = 'IV'
    else:
      train.loc[index, 'first_classification'] = a


    #print(index)
    #print(re.findall(r'.*\d', train.loc[index, 'SpType']))
    train.loc[index, 'second_classification'] = re.findall(r'.([0-9])', train.loc[index, 'SpType'])[0]
  except IndexError:
      train.loc[index, 'first_classification'] = 'IV'
      train.loc[index, 'second_classification'] = 4

  #print(re.split(r'\d[A-Za-z]*', i)).*\d

In [50]:
train = train.drop(['SpType'], axis=1)
train

,Vmag,Plx,e_Plx,B-V,Amag,TargetClass,first_bukva,first_classification,second_classification
0,6.901420,24.569658,0.862829,0.737416,20.449126,1,G,V,5
1,4.334196,2.198947,0.593309,1.153210,13.043324,0,G,I,2
2,7.873019,11.750465,0.616568,0.589166,17.736492,1,F,V,5
3,8.110014,2.143815,0.848508,1.322107,15.592469,0,K,III,2
4,8.025193,4.165622,0.899296,1.141646,16.379680,0,K,III,5
...,...,...,...,...,...,...,...,...,...
31636,7.561113,0.692340,0.843319,0.252874,12.542120,0,A,II,0
31637,8.078011,3.002784,0.689891,0.971966,15.379710,0,G,III,8
31638,7.065964,7.820498,0.885794,0.435381,16.737442,1,F,IV,3
31639,8.685452,2.643033,1.064647,0.988600,14.859882,0,K,III,0
31640,8.612488,19.959947,0.771636,0.611390,20.814352,1,G,V,3

In [51]:
from sklearn import preprocessing
 

l1 = preprocessing.LabelEncoder()
l1.fit(train['first_bukva'])
train['first_bukva'] = l1.transform(train['first_bukva'])

l2 = preprocessing.LabelEncoder()
l2.fit(train['first_classification'])
train['first_classification'] = l2.transform(train['first_classification'])

'''l3 = preprocessing.LabelEncoder()
l3.fit(train['second_classification'])
train['second_classification'] = l3.transform(train['second_classification'])
'''

train

,Vmag,Plx,e_Plx,B-V,Amag,TargetClass,first_bukva,first_classification,second_classification
0,6.901420,24.569658,0.862829,0.737416,20.449126,1,8,4,5
1,4.334196,2.198947,0.593309,1.153210,13.043324,0,8,0,2
2,7.873019,11.750465,0.616568,0.589166,17.736492,1,7,4,5
3,8.110014,2.143815,0.848508,1.322107,15.592469,0,12,2,2
4,8.025193,4.165622,0.899296,1.141646,16.379680,0,12,2,5
...,...,...,...,...,...,...,...,...,...
31636,7.561113,0.692340,0.843319,0.252874,12.542120,0,0,1,0
31637,8.078011,3.002784,0.689891,0.971966,15.379710,0,8,2,8
31638,7.065964,7.820498,0.885794,0.435381,16.737442,1,7,3,3
31639,8.685452,2.643033,1.064647,0.988600,14.859882,0,12,2,0
31640,8.612488,19.959947,0.771636,0.611390,20.814352,1,8,4,3

In [52]:
#from sklearn.preprocessing import MinMaxScaler

X = train.drop(['TargetClass'], axis=1)
y = train['TargetClass']
'''
scaler = MinMaxScaler([0,1])
X_n = scaler.fit_transform(X)
X_n'''

'\nscaler = MinMaxScaler([0,1])\nX_n = scaler.fit_transform(X)\nX_n'

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42, test_size = 1/3)

In [54]:
rfc = RandomForestClassifier(random_state = 42, n_jobs = -1)
rfc.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [55]:
pred = rfc.predict(X_test)

In [56]:
roc_auc_score(y_test, pred)

0.9597209651708986

In [75]:
test['first_bukva'] = 0
test['first_classification'] = 0
test['second_classification'] = 0
for index, row in test.iterrows():
  test.loc[index, 'first_bukva'] = re.split(r'\d', test.loc[index, 'SpType'])[0]
  try:
    a = re.findall(r'.*[0-9]([IV]*)', test.loc[index, 'SpType'])[-1]
    if a  not in ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII']:
      test.loc[index, 'first_classification'] = 'IV'
    else:
      test.loc[index, 'first_classification'] = a


    #print(index)
    #print(re.findall(r'.*\d', test.loc[index, 'SpType']))
    test.loc[index, 'second_classification'] = re.findall(r'.([0-9])', test.loc[index, 'SpType'])[0]
  except IndexError:
      test.loc[index, 'first_classification'] = 'IV'
      test.loc[index, 'second_classification'] = 4

  #print(re.split(r'\d[A-Za-z]*', i)).*\d

test

,Vmag,Plx,e_Plx,B-V,SpType,Amag,first_bukva,first_classification,second_classification
0,4.039519,13.596504,0.845101,-0.097823,F5V+...,15.774122,F,V,5
1,6.655719,4.010332,1.050017,1.386670,K5III,15.344976,K,III,5
2,6.405060,0.348855,0.961598,0.951503,B0IVpe,12.236103,B,IV,0
3,9.113068,2.954461,1.251422,1.002819,K1III,15.560838,K,III,1
4,6.107686,3.144180,0.475795,0.493345,G8II-IIIvar,12.771981,G,II,8
...,...,...,...,...,...,...,...,...,...
7906,8.255272,2.858885,0.822289,1.349195,M3III,16.438014,M,III,3
7907,6.255358,3.034436,0.449386,0.966053,K0III,13.898403,K,III,0
7908,8.643598,10.932145,0.947897,0.504383,G0V,18.980729,G,V,0
7909,9.400810,6.279361,1.332124,0.351073,F2V,16.872491,F,V,2
7910,8.792551,2.379289,1.451311,1.110596,K1III,15.737505,K,III,1

In [76]:
from sklearn import preprocessing
 

l4 = preprocessing.LabelEncoder()
l4.fit(test['first_bukva'])
test['first_bukva'] = l4.transform(test['first_bukva'])

l5 = preprocessing.LabelEncoder()
l5.fit(test['first_classification'])
test['first_classification'] = l5.transform(test['first_classification'])

'''l6 = preprocessing.LabelEncoder()
l6.fit(test['second_classification'])
test['second_classification'] = l6.transform(test['second_classification'])

'''
test

,Vmag,Plx,e_Plx,B-V,SpType,Amag,first_bukva,first_classification,second_classification
0,4.039519,13.596504,0.845101,-0.097823,F5V+...,15.774122,5,4,5
1,6.655719,4.010332,1.050017,1.386670,K5III,15.344976,8,2,5
2,6.405060,0.348855,0.961598,0.951503,B0IVpe,12.236103,2,3,0
3,9.113068,2.954461,1.251422,1.002819,K1III,15.560838,8,2,1
4,6.107686,3.144180,0.475795,0.493345,G8II-IIIvar,12.771981,6,1,8
...,...,...,...,...,...,...,...,...,...
7906,8.255272,2.858885,0.822289,1.349195,M3III,16.438014,10,2,3
7907,6.255358,3.034436,0.449386,0.966053,K0III,13.898403,8,2,0
7908,8.643598,10.932145,0.947897,0.504383,G0V,18.980729,6,4,0
7909,9.400810,6.279361,1.332124,0.351073,F2V,16.872491,5,4,2
7910,8.792551,2.379289,1.451311,1.110596,K1III,15.737505,8,2,1

In [77]:
test = test.drop(['SpType'], axis=1)
test

,Vmag,Plx,e_Plx,B-V,Amag,first_bukva,first_classification,second_classification
0,4.039519,13.596504,0.845101,-0.097823,15.774122,5,4,5
1,6.655719,4.010332,1.050017,1.386670,15.344976,8,2,5
2,6.405060,0.348855,0.961598,0.951503,12.236103,2,3,0
3,9.113068,2.954461,1.251422,1.002819,15.560838,8,2,1
4,6.107686,3.144180,0.475795,0.493345,12.771981,6,1,8
...,...,...,...,...,...,...,...,...
7906,8.255272,2.858885,0.822289,1.349195,16.438014,10,2,3
7907,6.255358,3.034436,0.449386,0.966053,13.898403,8,2,0
7908,8.643598,10.932145,0.947897,0.504383,18.980729,6,4,0
7909,9.400810,6.279361,1.332124,0.351073,16.872491,5,4,2
7910,8.792551,2.379289,1.451311,1.110596,15.737505,8,2,1

In [78]:
X = test
y = train['TargetClass']
'''from sklearn.preprocessing import MinMaxScaler




scaler = MinMaxScaler([0,1])
X_n = scaler.fit_transform(test)
X_n'''

'from sklearn.preprocessing import MinMaxScaler\n\n\n\n\nscaler = MinMaxScaler([0,1])\nX_n = scaler.fit_transform(test)\nX_n'

In [79]:
pred = rfc.predict(test)

In [80]:
pred = pd.Series(pred)

In [81]:
pred.to_csv('Result.csv')
pred_file = pd.read_csv('/content/Result.csv')

In [82]:
pred_file.rename(columns={'0': 'TargetClass','Unnamed: 0':'Number'}, inplace=True)

In [83]:
test=test.join(pred_file)

In [84]:
pred_final = test.drop(['Number'], axis='columns')

In [86]:
pred_final.to_csv('Result_final.csv',index=False)

In [87]:
final = pd.read_csv('Result_final.csv')
final = final.drop(['first_bukva', 'first_classification', 'second_classification'], axis = 1)
final

          Vmag        Plx     e_Plx       B-V       Amag  TargetClass
0     4.039519  13.596504  0.845101 -0.097823  15.774122            1
1     6.655719   4.010332  1.050017  1.386670  15.344976            0
2     6.405060   0.348855  0.961598  0.951503  12.236103            1
3     9.113068   2.954461  1.251422  1.002819  15.560838            0
4     6.107686   3.144180  0.475795  0.493345  12.771981            0
...        ...        ...       ...       ...        ...          ...
7906  8.255272   2.858885  0.822289  1.349195  16.438014            0
7907  6.255358   3.034436  0.449386  0.966053  13.898403            0
7908  8.643598  10.932145  0.947897  0.504383  18.980729            1
7909  9.400810   6.279361  1.332124  0.351073  16.872491            1
7910  8.792551   2.379289  1.451311  1.110596  15.737505            0

[7911 rows x 6 columns]

In [88]:
final = final.reindex(columns=['Vmag', 'Plx', 'e_Plx', 'B-V', 'SpType', 'Amag', 'TargetClass'])
final

          Vmag        Plx     e_Plx       B-V  SpType       Amag  TargetClass
0     4.039519  13.596504  0.845101 -0.097823     NaN  15.774122            1
1     6.655719   4.010332  1.050017  1.386670     NaN  15.344976            0
2     6.405060   0.348855  0.961598  0.951503     NaN  12.236103            1
3     9.113068   2.954461  1.251422  1.002819     NaN  15.560838            0
4     6.107686   3.144180  0.475795  0.493345     NaN  12.771981            0
...        ...        ...       ...       ...     ...        ...          ...
7906  8.255272   2.858885  0.822289  1.349195     NaN  16.438014            0
7907  6.255358   3.034436  0.449386  0.966053     NaN  13.898403            0
7908  8.643598  10.932145  0.947897  0.504383     NaN  18.980729            1
7909  9.400810   6.279361  1.332124  0.351073     NaN  16.872491            1
7910  8.792551   2.379289  1.451311  1.110596     NaN  15.737505            0

[7911 rows x 7 columns]

In [89]:
final.to_csv('Result_final.csv',index=False)