In [4]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
          'Это утро, радость эта,',
          'Эта мощь и дня и света,',
          'Этот синий день,',
         'Этот крик и вереницы,',
          'Эти стаи, эти птицы,',
          'Этот говор вод...',

]

corpus

['Это утро, радость эта,',
 'Эта мощь и дня и света,',
 'Этот синий свод,',
 'Этот крик и вереницы,',
 'Эти стаи, эти птицы,',
 'Этот говор вод...']

In [2]:
# Создаем модель векторизации текста
vectorizer = TfidfVectorizer()

# токенезация текста и построение словоря
vectorizer.fit(corpus)

# summarize
print(vectorizer.vocabulary_)
print(vectorizer.idf_)

{'это': 15, 'утро': 12, 'радость': 7, 'эта': 13, 'мощь': 5, 'дня': 3, 'света': 8, 'этот': 16, 'синий': 10, 'свод': 9, 'крик': 4, 'вереницы': 0, 'эти': 14, 'стаи': 11, 'птицы': 6, 'говор': 2, 'вод': 1}
[2.25276297 2.25276297 2.25276297 2.25276297 2.25276297 2.25276297
 2.25276297 2.25276297 2.25276297 2.25276297 2.25276297 2.25276297
 2.25276297 1.84729786 2.25276297 2.25276297 1.55961579]

In [5]:
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform(corpus)

feature_names = vectorizer.get_feature_names()
print("Feature names", feature_names)

dense = vectors.todense()

denselist = dense.tolist()

df2 = pd.DataFrame(denselist, columns=feature_names)
df2

Feature names ['вереницы', 'вод', 'говор', 'дня', 'крик', 'мощь', 'птицы', 'радость', 'света', 'свод', 'синий', 'стаи', 'утро', 'эта', 'эти', 'это', 'этот']

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,вереницы,вод,говор,дня,крик,мощь,птицы,радость,света,свод,синий,стаи,утро,эта,эти,это,этот
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.521823,0.000000,0.000000,0.000000,0.000000,0.521823,0.427903,0.000000,0.521823,0.000000
1,0.000000,0.000000,0.000000,0.521823,0.000000,0.521823,0.000000,0.000000,0.521823,0.000000,0.000000,0.000000,0.000000,0.427903,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.635091,0.635091,0.000000,0.000000,0.000000,0.000000,0.000000,0.439681
3,0.635091,0.000000,0.000000,0.000000,0.635091,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.439681
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.408248,0.000000,0.000000,0.000000,0.000000,0.408248,0.000000,0.000000,0.816497,0.000000,0.000000
5,0.000000,0.635091,0.635091,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.439681

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
          'Это утро, радость эта,',
          'Эта мощь и дня и света,',
          'Этот синий день,',
         'Этот крик и вереницы,',
          'Эти стаи, эти птицы,',
          'Это утро вод...',

]

# Создаем модель векторизации текста
# (1,3)
vectorizer = TfidfVectorizer(ngram_range=(2,2))

# токенезация текста и построение словоря
vectors = vectorizer.fit_transform(corpus)

feature_names = vectorizer.get_feature_names()

dense = vectors.todense()

denselist = dense.tolist()

df2 = pd.DataFrame(denselist, columns=feature_names)
df2

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,дня света,крик вереницы,мощь дня,радость эта,синий день,стаи эти,утро вод,утро радость,эта мощь,эти птицы,эти стаи,это утро,этот крик,этот синий
0,0.00000,0.000000,0.00000,0.611713,0.000000,0.00000,0.000000,0.611713,0.00000,0.00000,0.00000,0.501613,0.000000,0.000000
1,0.57735,0.000000,0.57735,0.000000,0.000000,0.00000,0.000000,0.000000,0.57735,0.00000,0.00000,0.000000,0.000000,0.000000
2,0.00000,0.000000,0.00000,0.000000,0.707107,0.00000,0.000000,0.000000,0.00000,0.00000,0.00000,0.000000,0.000000,0.707107
3,0.00000,0.707107,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.00000,0.00000,0.000000,0.707107,0.000000
4,0.00000,0.000000,0.00000,0.000000,0.000000,0.57735,0.000000,0.000000,0.00000,0.57735,0.57735,0.000000,0.000000,0.000000
5,0.00000,0.000000,0.00000,0.000000,0.000000,0.00000,0.773262,0.000000,0.00000,0.00000,0.00000,0.634086,0.000000,0.000000